name = "merlin-s25-proxy"
main = "src/index.js"
compatibility_date = "2026-03-11"
workers_dev = true
routes = [
  { pattern = "merlin.smajor.org", custom_domain = true }
]

[vars]
ORIGIN_BASE = "http://pljfe3r2bh859ela04v9vrrh5s.ingress.jjozzietech.com.au"
ORIGIN_HOST_HEADER = "pljfe3r2bh859ela04v9vrrh5s.ingress.jjozzietech.com.au"
PROXY_TIMEOUT_MS = "30000"
PROXY_RETRIES = "0"
